Headache:
  extensions:
    - ".ha"

  default:
    color: "#DBB4AE"

  identifier:
    color: "#9B785B"

  number:
    color: "#A2AD91"

  string:
    color: "#A2AD91"

  comment:
    color: "#28FF37"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#D6B62A"
      operators:
        - "@"
        - "+"
        - "-"
        - "*"
        - "/"

      keywords:
        - "as"

    - color: "#E84855"
      keywords:
        - "return"
        - "while"
        - "if"
        - "else"
    - color: "#00C3FF"
      keywords:
        - "void"
        - "byte"
        - "short"
        - "int"