Headache:
  extensions:
    - ".ha"

  default:
    color: "#3185FC"

  string:
    color: "#D7C62A"

  group:
    - color: "#D6B62A"
      operators:
        - "@"
        - "+"
        - "-"
        - "*"
        - "/"

      keywords:
        - "as"

    - color: "#E84855"
      keywords:
        - "return"
        - "while"
        - "if"
        - "else"
    - color: "#BBA855"
      keywords:
        - "void"
        - "byte"
        - "short"
        - "int"